data:
  low: [-1.0, -1.0]
  high: [1.0, 1.0]
  num_points_range: [100, 101] # high not included
  batch_size: 2 # batch size per gpu
  outliers_ratio_range: [0.4, 0.6]
  cov_eigenvalues_range: [0.02, 0.05]
  ds_size: 1000 # batches per epoch
  num_workers: 4

model:
  num_scales: 3
  min_scale_multiplier: 0.2
  max_scale_multiplier: 0.8
  feat_trans_loss_weight: 0.01
  lr: 0.0001