data:
  low: '[-1.0] * 1000'
  high: '[1.0] * 1000'
  num_points_range: [500, 501] # high not included
  batch_size: 6 # batch size per gpu in DDP mode or overall in DP mode
  outliers_ratio_range: [0.7, 0.8]
  cov_eigenvalues_range: [0.005, 0.05]
  ds_size: 1000 # batches per epoch
  num_workers: 24

model:
  num_iter: 5
  feat_trans_loss_weight: 0.001
  lr: 0.0001